version: '3.8'

services:
  db:
    image: postgres:15-alpine
    env_file:
      - ../.env
    environment:
        POSTGRES_DB: orbitalos
        POSTGRES_USER: orbitalos
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orbitalos"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ..
      dockerfile: orbitalos/infra/Dockerfile
    env_file:
      - ../.env
    environment:
        DATABASE_URL: ${DATABASE_URL}
        JWT_SECRET: ${JWT_SECRET}
        RUST_LOG: info
        AES_256_KEY: ${AES_256_KEY}
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../orbitalos/backend:/app/backend:ro
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../orbitalos/frontend/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
